package lt.vu.usecases.mybatis.dao;

import java.util.List;
import lt.vu.usecases.mybatis.model.Grade;

public interface GradeMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PUBLIC.GRADE
     *
     * @mbg.generated Wed Mar 28 12:32:43 EEST 2018
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PUBLIC.GRADE
     *
     * @mbg.generated Wed Mar 28 12:32:43 EEST 2018
     */
    int insert(Grade record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PUBLIC.GRADE
     *
     * @mbg.generated Wed Mar 28 12:32:43 EEST 2018
     */
    Grade selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PUBLIC.GRADE
     *
     * @mbg.generated Wed Mar 28 12:32:43 EEST 2018
     */
    List<Grade> selectAll();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PUBLIC.GRADE
     *
     * @mbg.generated Wed Mar 28 12:32:43 EEST 2018
     */
    int updateByPrimaryKey(Grade record);
}